#!/bin/bash
#-------------------------------------------------------------------------------
# Nek5000 build file
#-------------------------------------------------------------------------------

# source path 
#SOURCE_ROOT="/ccs/home/kekezhai/CMTHybrid/CMTHybrid_works/nek5/trunk/nek"
SOURCE_ROOT="/ccs/proj/csc188/titan/CMT-bone-hybrid/HybrideCMTBone-newcurtainTestcase-master/nek5/trunk/nek"
#"/cise/research/hpc/tmishra/hybrid/paper/paper/hybrid/fortran/cmtbone2/nek5/trunk/nek"
#SOURCE_ROOT="/ccs/home/tania/cmtbone2/nek5/trunk/nek"
SOURCE_ROOT2="$SOURCE_ROOT/cmthybrid" 

# Fortran/C compiler
F77="ftn -mcmodel=medium"
CC="cc"
NVCC="nvcc"

# pre-processor list (set to "?" to get a list of available symbols)
#PPLIST="CMTNEK EXTBAR MPIIO" 

# generic compiler flags
#G="-g"

# linking flags
#USR_LFLAGS="-L/usr/lib -lfoo"
#USR_LFLAGS="-I/usr/local/tools/essl/5.1/include -L/usr/local/tools/essl/5.1/lib -lesslbg"

###############################################################################
# WHAT FOLLOWS ARE OPTIONAL SETTINGS
###############################################################################

# MPI (default true)
# IFMPI="false"

# profiling (default false)
# IFPROFILING="true"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# enable VisIt in situ
#  Note: you can override the lib and include paths. VISIT_LIB and VISIT_INC
#  If VISIT_STOP is set the simulation will stop after first step and wait
#  for VisIt to connect.
#IFVISIT=true
#VISIT_INSTALL="/path/to/visit/current/linux-x86_64/"
#VISIT_STOP=true

# paths
#SOURCE_ROOT_CORE="$SOURCE_ROOT/core"
#SOURCE_ROOT_JL="$SOURCE_ROOT/jl"
#SOURCE_ROOT_CMT="$SOURCE_ROOT/core/cmt"

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
fi
# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc.cmthybrid
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
